services:
  whatsgpt:
    build: .
    env_file:
      - .env
    volumes:
      - ./authentication:/app/authentication
      - ./messageHistories.json:/app/messageHistories.json
    restart: unless-stopped